# MySQL.  Versions 5.0+ are recommended.
#

# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
#
default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: readit_development

test:
  <<: *default
  database: readit_test

production:
  <<: *default
  database: readit_production

